Pardon the copy and paste from the [[https://github.com/thingywhat/spankingTubeDownloader.js][SpankingTubeDownloader README]], but
a good majority of it is relevant here too...

xvideosDownloader.js is a userscript that changes the download button
on [[http://www.xvideos.com/][XVideos]] (*NSFW*) video pages to not require you to sign into an
account, or even have one for that matter.

XVideos already allows users to download videos, but a lot of us may
not want to make an account to do so if we are unsure about the site
yet...

* Requirements
This script should work the following browser versions:

- Pretty much any version of Firefox that can use [[https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/][Greasemonkey]].
- With the built-in userscript capabilities of Opera 10 to 12.16,
  Google Chrome, or Chromium.
- With [[https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en][Tampermonkey]] for Opera 15+.

It is also very likely to work with Google Chrome mobile with
[[https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en][Tampermonkey]], but this has not been tested.

* Installation
Depending on your browser, ensure you have the proper extensions
installed as detailed in Requirements. (If you need any, of course..!)

** Firefox
1) Navigate here [[https://raw.githubusercontent.com/thingywhat/xvideosDownloader.js/master/xvideosDownloader.user.js][xvideosDownloader.user.js]] and accept the install.
6) Viola! You now can now download videos from xVideos!

** Opera 10-12.5
1) Visit [[https://raw.githubusercontent.com/thingywhat/xvideosDownloader.js/master/xvideosDownloader.user.js][xvideosDownloader.user.js]].
2) Save the script somewhere you'll remember.
3) Navigate Opera -> Settings -> Preferences -> Advanced -> Content ->
   JavaScript Options
4) Point the "User JavaScript folder" to the folder containing the
   script
5) You should now have download links. Congrats~!

** Chrome, Chromium
1) Download [[https://raw.githubusercontent.com/thingywhat/xvideosDownloader.js/master/xvideosDownloader.user.js][xvideosDownloader.user.js]] somewhere you'll remember...
2) Visit Menu -> Tools -> Extensions
3) Drag the script you downloaded onto the window.
4) Accept the script install.
5) Have fun!

** Opera 15+
1) Copy the full contents of [[https://raw.githubusercontent.com/thingywhat/xvideosDownloader.js/master/xvideosDownloader.user.js][xvideosDownloader.user.js]]
2) Click the Tampermonkey button on your install.
3) Select "Add a new script..."
4) Paste the script into the Editor window.
5) Click the "Save" icon.
6) Have fun! You now have it installed.
